name: Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: [0.37.0]
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
        run: deno test

